import {CoordinateFields} from '../ranking/CoordinateFields.tsx';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {getClient} from '../../../../../packages/data/src/client.ts';
import {listDiscoveries,saveDiscovery} from '../../../../../packages/data/src/discovery-client.ts';
import {blankDiscovery,validateDiscovery,type DiscoveryCategory,type DiscoveryInput,type DiscoveryItem} from '../../../../../packages/data/src/discovery.ts';
import {provinces,safeWebUrl} from '../../../../../packages/data/src/museums.ts';
import {categories} from '../../../../../packages/domain/src/navigation.ts';
export function DiscoveryAdmin({category}:{category:DiscoveryCategory}){
 const [client,setClient]=useState<SupabaseClient|null>(null),[mode,setMode]=useState('loading'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState('');
 const [rows,setRows]=useState<DiscoveryItem[]>([]),[inventory,setInventory]=useState<DiscoveryItem[]>([]),[total,setTotal]=useState(0),[search,setSearch]=useState(''),[province,setProvince]=useState(''),[page,setPage]=useState(0),[refresh,setRefresh]=useState(0);
 const [selected,setSelected]=useState<DiscoveryInput|null>(null),[existing,setExisting]=useState<DiscoveryItem|null>(null),[notes,setNotes]=useState(''),[key,setKey]=useState(0);const selection=useRef(0);
 const title=categories.find(c=>c.id===category)!.name;
 useEffect(()=>{let active=true;let off:(()=>void)|undefined;async function inspect(c:SupabaseClient){const session=await c.auth.getSession();const role=session.data.session?await c.rpc('kk_is_editor'):null;if(active)setMode(!session.data.session?'login':role?.data===true?'editor':'denied');}
 getClient().then(async c=>{if(!active)return;setClient(c);await inspect(c);const {data}=c.auth.onAuthStateChange(()=>{setTimeout(()=>{if(active)void inspect(c);},0);});off=()=>data.subscription.unsubscribe();}).catch(async()=>{if(!active)return;setMode('preview');try{const r=await fetch(`/kunstkiezer/${category}.json`);if(!r.ok)throw Error();const data=await r.json();if(active)setInventory(data);}catch{if(active)setMessage('De inventaris kon niet worden geladen.');}});return()=>{active=false;off?.();};},[category]);
 useEffect(()=>{if(mode!=='editor'||!client)return;let active=true;const timer=setTimeout(()=>{listDiscoveries(client,category,search,province,'',true,page).then(r=>{if(active){setRows(r.rows);setTotal(r.total);}}).catch(e=>{if(active)setMessage(e.message);});},200);return()=>{active=false;clearTimeout(timer);};},[client,mode,category,search,province,page,refresh]);
 async function login(e:FormEvent){e.preventDefault();if(!client)return;const {error}=await client.auth.signInWithPassword({email,password});setPassword('');setMessage(error?'Aanmelden is niet gelukt. Controleer je gegevens.':'');}
 async function choose(r:DiscoveryItem){const token=++selection.current;setSelected(null);setMessage('');let text='';if(mode==='editor'&&client){const {data,error}=await client.from('kk_discovery_editorial').select('review_notes').eq('discovery_id',r.id).maybeSingle();if(token!==selection.current)return;if(error){setMessage('Redactienotities konden niet worden geladen.');return;}text=data?.review_notes??'';}setNotes(text);setExisting(mode==='editor'?r:null);setSelected(r);setKey(k=>k+1);}
 const filtered=inventory.filter(r=>(!province||r.province===province)&&`${r.name} ${r.city} ${r.creator}`.toLowerCase().includes(search.toLowerCase()));const visible=mode==='preview'?filtered.slice(page*30,page*30+30):rows;const count=mode==='preview'?filtered.length:total;
 return <><a className="back-link" href="/kunstkiezer/beheer">← Alle verzamelingen</a><header className="page-heading"><p className="eyebrow">Redactie</p><h1>{title}<span className="accent">.</span></h1><p>Bekijk en bewerk de selectie, bronnen en tags.</p></header>
 {mode==='loading'&&<p role="status">Databaseverbinding controleren…</p>}{mode==='preview'&&<p className="notice">Inventarispreview — niet verbonden met Supabase. Opslaan is hier niet mogelijk.</p>}
 {mode==='login'&&<form className="login-form" onSubmit={e=>void login(e)}><h2>Aanmelden als redacteur</h2><label>E-mail<input type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Wachtwoord<input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary-button">Aanmelden met wachtwoord</button><button type="button" onClick={async()=>{if(!email.trim()||!client){setMessage('Vul je e-mailadres in.');return;}const {error}=await client.auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:window.location.origin+`/kunstkiezer/beheer/${category}`}});setMessage(error?'De aanmeldlink kon niet worden verstuurd.':'Aanmeldlink aangevraagd. Bekijk je e-mail.');}}>Stuur mij een aanmeldlink</button></form>}
 {mode==='denied'&&<p>Dit account heeft geen redactierechten.</p>}{(mode==='editor'||mode==='denied')&&<button onClick={()=>{void client?.auth.signOut();setSelected(null);}}>Afmelden</button>}{message&&<p role="status" className="notice">{message}</p>}
 {(mode==='editor'||mode==='preview')&&<><div className="filters"><label>Zoek op naam, maker of plaats<input type="search" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label><label>Provincie<select value={province} onChange={e=>{setProvince(e.target.value);setPage(0);}}><option value="">Alle provincies</option>{provinces.map(p=><option key={p}>{p}</option>)}</select></label>{mode==='editor'&&<button onClick={()=>{selection.current++;setSelected(blankDiscovery(category));setExisting(null);setNotes('');setKey(k=>k+1);}}>Vermelding toevoegen</button>}</div><p role="status">{count} vermeldingen · pagina {page+1} van {Math.max(1,Math.ceil(count/30))}</p><a href={`/kunstkiezer/${category}.json`} download>Download onderzoeksbestand</a><div className="admin-layout"><section className="museum-list" aria-label="Vermeldingen">{visible.map(r=><button key={r.id} className="museum-row" onClick={()=>void choose(r)}><strong>{r.name}</strong><span>{r.city} · {r.province}</span><small>{r.publication_status==='published'?'Gepubliceerd':'Concept'}{r.operating_status!=='open'?' · bezoekstatus controleren':''}</small></button>)}<div className="pagination"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Vorige</button><button disabled={(page+1)*30>=count} onClick={()=>setPage(p=>p+1)}>Volgende</button></div></section>{selected?<DiscoveryForm key={key} value={selected} notes={notes} canSave={mode==='editor'} onSave={async(r,n)=>{if(!client)throw Error('Geen databaseverbinding.');const token=selection.current;const saved=await saveDiscovery(client,r,existing,n);if(token===selection.current)setExisting(saved);setRefresh(x=>x+1);}}/>:<div className="empty-state"><h2>Kies een vermelding</h2><p>Open een tekstveld links om de gegevens te bewerken.</p></div>}</div></>}
 </>;
}
function DiscoveryForm({value,notes:initialNotes,canSave,onSave}:{value:DiscoveryInput;notes:string;canSave:boolean;onSave:(r:DiscoveryInput,n:string)=>Promise<void>}){
 const [r,setR]=useState(value),[notes,setNotes]=useState(initialNotes),[tagsText,setTagsText]=useState(value.tags.join(', ')),[errors,setErrors]=useState<Record<string,string>>({}),[status,setStatus]=useState(''),[saving,setSaving]=useState(false);const form=useRef<HTMLFormElement>(null);
 function patch<K extends keyof DiscoveryInput>(k:K,v:DiscoveryInput[K]){setR(old=>({...old,[k]:v}));setErrors(old=>{const x={...old};delete x[k];return x;});setStatus('');}
 async function submit(e:FormEvent){e.preventDefault();const input={...r,tags:Array.from(new Set(tagsText.split(',').map(t=>t.trim().toLowerCase()).filter(Boolean)))};const next=validateDiscovery(input);setErrors(next);if(Object.keys(next).length){setStatus('Vul de rood gemarkeerde velden aan.');requestAnimationFrame(()=>{const el=form.current?.querySelector<HTMLElement>('[aria-invalid="true"]');el?.focus();el?.scrollIntoView({behavior:'smooth',block:'center'});});return;}if(!canSave)return;setSaving(true);try{await onSave(input,notes);setStatus('Opgeslagen in Supabase.');}catch(e){setStatus(e instanceof Error?e.message:'Opslaan mislukt.');}finally{setSaving(false);}}
 function field(k:'name'|'city'|'street_address'|'website_url'|'creator'|'year'|'summary'|'selection_reason'|'visit_notes',label:string,area=false){return <label>{label}{area?<textarea aria-label={label} aria-invalid={!!errors[k]} value={r[k]} onChange={e=>patch(k,e.target.value)}/>:<input aria-label={label} aria-invalid={!!errors[k]} value={r[k]} onChange={e=>patch(k,e.target.value)}/>} {errors[k]&&<span className="field-error">{errors[k]}</span>}</label>;}
 return <form ref={form} onSubmit={e=>void submit(e)} className="museum-form" noValidate><h2>Vermelding bewerken</h2><div className="form-grid">{field('name','Naam')}{field('city','Plaats')}<label>Provincie<select value={r.province} onChange={e=>patch('province',e.target.value)}><option value="">Nog invullen</option>{provinces.map(p=><option key={p}>{p}</option>)}</select></label>{field('street_address','Adres of locatie')}{field('creator',r.category==='architectuur'?'Architect':'Kunstenaar / maker')}{field('year','Jaar / periode')}{field('website_url','Website')}<label>Bezoekstatus<select aria-label="Bezoekstatus" aria-invalid={!!errors.operating_status} value={r.operating_status} onChange={e=>patch('operating_status',e.target.value as DiscoveryInput['operating_status'])}><option value="open">Open</option><option value="unknown">Nog controleren</option><option value="temporarily_closed">Tijdelijk gesloten</option><option value="closed">Gesloten / verdwenen</option></select>{errors.operating_status&&<span className="field-error">{errors.operating_status}</span>}</label><label>Publicatie<select aria-label="Publicatie" value={r.publication_status} onChange={e=>patch('publication_status',e.target.value as DiscoveryInput['publication_status'])}><option value="draft">Concept</option><option value="published">Gepubliceerd</option><option value="archived">Archief</option></select></label></div>
 <CoordinateFields value={r} errors={errors} onChange={change=>{setR(old=>({...old,...change}));setErrors({});setStatus('');}}/>{r.category==='evenementen'&&<div className="form-grid">{(['starts_on','ends_on'] as const).map(k=><label key={k}>{k==='starts_on'?'Begindatum':'Einddatum'}<input type="date" aria-label={k==='starts_on'?'Begindatum':'Einddatum'} aria-invalid={!!errors[k]} value={r[k]??''} onChange={e=>patch(k,e.target.value||null)}/>{errors[k]&&<span className="field-error">{errors[k]}</span>}</label>)}</div>}
 {field('summary','Beschrijving (maximaal 80 woorden)',true)}<p>{r.summary.trim().split(/\s+/).filter(Boolean).length} / 80 woorden</p>{field('selection_reason','Waarom geselecteerd?',true)}{field('visit_notes','Praktische bezoekinformatie',true)}<label>Tags, gescheiden door komma’s<input aria-label="Tags, gescheiden door komma’s" aria-invalid={!!errors.tags} value={tagsText} onChange={e=>{setTagsText(e.target.value);setErrors(old=>{const next={...old};delete next.tags;return next;});setStatus('');}}/>{errors.tags&&<span className="field-error">{errors.tags}</span>}</label>
 <fieldset><legend>Bronnen</legend>{errors.sources&&<p className="field-error">{errors.sources}</p>}{r.sources.map((s,i)=><div className="source-fields" key={i}><label>Bronnaam {i+1}<input value={s.provider} onChange={e=>patch('sources',r.sources.map((x,j)=>j===i?{...x,provider:e.target.value}:x))}/></label><label>Bronlink {i+1}<input aria-invalid={!!errors[`source-${i}`]} value={s.url} onChange={e=>patch('sources',r.sources.map((x,j)=>j===i?{...x,url:e.target.value}:x))}/></label>{errors[`source-${i}`]&&<span className="field-error">{errors[`source-${i}`]}</span>}{safeWebUrl(s.url)&&<a href={s.url} target="_blank" rel="noopener noreferrer">Bekijk bron ↗</a>}<button type="button" onClick={()=>patch('sources',r.sources.filter((_,j)=>i!==j))}>Bron {i+1} verwijderen</button></div>)}<button type="button" aria-invalid={!!errors.sources} onClick={()=>patch('sources',[...r.sources,{provider:'',url:'',retrieved_at:new Date().toISOString()}])}>Bron toevoegen</button></fieldset>
 <fieldset><legend>Foto’s</legend>{r.photos.map((p,i)=><div className="source-fields" key={i}>{safeWebUrl(p.url)&&<img className="editor-photo" src={p.url} alt={p.caption}/>} {(['url','caption','credit','source_url','license'] as const).map(k=><label key={k}>{{url:'Fotolink',caption:'Onderschrift',credit:'Maker',source_url:'Fotobron',license:'Licentie'}[k]} {i+1}<input aria-invalid={k==='url'&&!!errors[`photo-${i}`]} value={p[k]} onChange={e=>patch('photos',r.photos.map((x,j)=>i===j?{...x,[k]:e.target.value}:x))}/></label>)}{errors[`photo-${i}`]&&<p className="field-error">{errors[`photo-${i}`]}</p>}<button type="button" onClick={()=>patch('photos',r.photos.filter((_,j)=>j!==i))}>Foto {i+1} verwijderen</button></div>)}<button type="button" onClick={()=>patch('photos',[...r.photos,{url:'',caption:'',credit:'',source_url:'',license:''}])}>Foto toevoegen</button></fieldset>
 <label>Interne redactienotities<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>{status&&<p className="notice" role="status">{status}</p>}<button disabled={!canSave||saving} className="primary-button">{saving?'Opslaan…':'Opslaan in Supabase'}</button></form>;
}
