import {useProfile} from '../profile/useProfile.ts';
import {TasteMatches,TasteSorting,VisitStatus,VisitNotes} from '../profile/Personalization.tsx';
import {useEffect,useState} from 'react';
import {getClient} from '../../../../../packages/data/src/client.ts';
import {listDiscoveries} from '../../../../../packages/data/src/discovery-client.ts';
import {amsterdamDay,type DiscoveryCategory,type DiscoveryItem} from '../../../../../packages/data/src/discovery.ts';
import {provinces,safeWebUrl} from '../../../../../packages/data/src/museums.ts';
export function DiscoveryCatalog({category}:{category:DiscoveryCategory}){
 const profile=useProfile();const [personalized,setPersonalized]=useState(true);const taste=personalized?profile.tags:[];const tasteKey=JSON.stringify(taste);
 const [search,setSearch]=useState(''),[province,setProvince]=useState(''),[tag,setTag]=useState(''),[page,setPage]=useState(0),[rows,setRows]=useState<DiscoveryItem[]>([]),[total,setTotal]=useState(0),[status,setStatus]=useState('Laden…'),[day,setDay]=useState(amsterdamDay());
 useEffect(()=>{const id=setInterval(()=>setDay(amsterdamDay()),60000);return()=>clearInterval(id);},[]);
 useEffect(()=>{let active=true;setStatus('Laden…');const timer=setTimeout(()=>{getClient().then(c=>listDiscoveries(c,category,search,province,tag,false,page,taste)).then(r=>{if(active){setRows(r.rows);setTotal(r.total);setStatus('');}}).catch(e=>{if(active){setRows([]);setStatus(e.message);}});},200);return()=>{active=false;clearTimeout(timer);};},[category,search,province,tag,page,day,tasteKey]);
 return <><TasteSorting tags={profile.tags} personalized={personalized} onChange={v=>{setPersonalized(v);setPage(0);}}/><div className="filters"><label>Zoek op naam, maker of plaats<input type="search" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label><label>Provincie<select value={province} onChange={e=>{setProvince(e.target.value);setPage(0);}}><option value="">Heel Nederland</option>{provinces.map(p=><option key={p}>{p}</option>)}</select></label><label>Tag<input placeholder="Bijvoorbeeld fotografie" value={tag} onChange={e=>{setTag(e.target.value);setPage(0);}}/></label></div>
 {category==='evenementen'&&<p>Lopende tentoonstellingen en evenementen, en activiteiten die binnen één maand beginnen. Controleer openingstijden bij de organisator.</p>}
 <p role="status">{status||`${total} resultaten`}</p>{!status&&!rows.length&&<p>Geen resultaten voor deze selectie.</p>}
 <div className="museum-grid">{rows.map(r=><article className="museum-card" key={r.id}><p className="eyebrow">{[r.city,r.province].filter(Boolean).join(' · ')}</p><h2>{r.name}</h2><TasteMatches tags={r.tags} preferences={taste}/><VisitStatus status={r.operating_status} missingLocation={!r.street_address}/>{r.creator&&<p>{r.creator}{r.year&&` · ${r.year}`}</p>}{r.starts_on&&r.ends_on&&<p><time dateTime={r.starts_on}>{r.starts_on.split('-').reverse().join('-')}</time> t/m <time dateTime={r.ends_on}>{r.ends_on.split('-').reverse().join('-')}</time></p>}
 <div className="museum-photos">{r.photos.filter(p=>safeWebUrl(p.url)).map((p,i)=><figure key={i}><img src={p.url} alt={p.caption||r.name} loading="lazy"/><figcaption>{p.caption} · {p.credit} · <a href={safeWebUrl(p.source_url)??undefined} target="_blank" rel="noopener noreferrer">{p.license}</a></figcaption></figure>)}</div>
 <p>{r.summary}</p><p>{r.street_address}</p><VisitNotes notes={r.visit_notes}/><div className="tag-list">{r.tags.map(t=><button type="button" key={t} onClick={()=>{setTag(t);setPage(0);}}>{t}</button>)}</div><details><summary>Waarom geselecteerd?</summary><p>{r.selection_reason}</p>{r.sources.filter(s=>safeWebUrl(s.url)).map((s,i)=><p key={i}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.provider} ↗</a></p>)}</details>{safeWebUrl(r.website_url)&&<a className="text-button" href={r.website_url} target="_blank" rel="noopener noreferrer">Bezoekinformatie ↗</a>}</article>)}</div>
 {total>30&&<div className="pagination"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Vorige</button><span>Pagina {page+1} van {Math.ceil(total/30)}</span><button disabled={(page+1)*30>=total} onClick={()=>setPage(p=>p+1)}>Volgende</button></div>}</>;
}
