// Tags from the curated museum and discovery research files.
export const catalogueTags:string[]=[
  "11fountains",
  "19e eeuw",
  "20e eeuw",
  "abstract",
  "abstract expressionisme",
  "affiches",
  "aluminium",
  "ambacht",
  "amsterdam-zuidoost",
  "amsterdamse school",
  "animatie",
  "antiracisme",
  "arboretum",
  "architectuur",
  "art deco",
  "art nouveau",
  "astronomie",
  "avondprogramma",
  "baksteen",
  "beeldcultuur",
  "beeldende kunst",
  "beeldenensemble",
  "beeldenroute",
  "beeldentuin",
  "beeldhouwkunst",
  "beton",
  "bewegend beeld",
  "bibliotheken",
  "bijzondere huisvesting",
  "bio-art",
  "biokunst",
  "bioscopen en theaters",
  "bloemen",
  "bomen",
  "borduurkunst",
  "bos",
  "brabant",
  "brons",
  "carel willink",
  "cartoons",
  "civiele werken",
  "collectie",
  "conceptuele kunst",
  "consumptiecultuur",
  "dada",
  "dans",
  "de stijl",
  "delfts blauw",
  "design",
  "dieren",
  "digitale cultuur",
  "digitale kunst",
  "digitale presentatie",
  "documentair",
  "documentaire fotografie",
  "drukwerk",
  "ecologie",
  "eve arnold",
  "evenement",
  "experiment",
  "expressionisme",
  "familie",
  "fantasie",
  "festival",
  "fiep westendorp",
  "figuratief",
  "figuratieve kunst",
  "film",
  "fontein",
  "fotografie",
  "games",
  "gebouwen",
  "gebouwen voor de gezondheidszorg",
  "geluidskunst",
  "geometrie",
  "gereconstrueerd",
  "glas",
  "glas-in-lood",
  "glaskunst",
  "graffiti",
  "grafiek",
  "grafisch ontwerp",
  "haagse school",
  "hedendaags ontwerp",
  "hedendaagse architectuur",
  "hedendaagse kunst",
  "herdenken",
  "hergebruik",
  "historische architectuur",
  "hotels, cafés, restaurants",
  "iconen",
  "identiteit",
  "illustratie",
  "immersieve kunst",
  "impressionisme",
  "inclusief",
  "industrieel erfgoed",
  "installaties",
  "interactief",
  "jan mankes",
  "japanse kunst",
  "jong talent",
  "jongerencultuur",
  "kantoorgebouwen",
  "kasteel",
  "keramiek",
  "kinderen",
  "kleur",
  "kleurrijke bloemen",
  "klimaat",
  "kunst",
  "kunst in de openbare ruimte",
  "kunst in openbare ruimte",
  "kunst rond 1900",
  "kunstdepot",
  "kunstenaarsboeken",
  "kunstenaarskolonie",
  "kunstenaarsmuseum",
  "kunstenaarsvereniging",
  "kunsthal",
  "kunstvervalsing",
  "kunstwandeling",
  "land art",
  "landgoed",
  "landschap",
  "landschapskunst",
  "leo gestel",
  "licht",
  "lichtkunst",
  "lithografie",
  "maatschappij",
  "magisch realisme",
  "manuscripten",
  "marmer",
  "marten toonder",
  "materialen",
  "mediakunst",
  "mens en natuur",
  "metaal",
  "meubelontwerp",
  "middeleeuwse kunst",
  "migratie",
  "miniatuurkunst",
  "minimalisme",
  "mode",
  "moderne kunst",
  "modernisme",
  "monument",
  "monumentaal gebouw",
  "monumenten",
  "musea en tentoonstellingsgebouwen",
  "museumnacht",
  "museumtuin",
  "museumwoning",
  "muurschilderingen",
  "muziek",
  "mythen",
  "nacht",
  "naoorlogse architectuur",
  "naoorlogse kunst",
  "natuur",
  "naïeve kunst",
  "negentiende eeuw",
  "neogotiek",
  "nul",
  "objecten",
  "omroepgebouwen",
  "onderwijsgebouwen",
  "onderzoek",
  "openlucht",
  "optische illusies",
  "oude kunst",
  "oude meesters",
  "outsider art",
  "overheidsgebouwen",
  "panorama",
  "papierkunst",
  "park",
  "performance",
  "picturalisme",
  "piet mondriaan",
  "pointillisme",
  "polderlandschap",
  "popart",
  "porselein",
  "portret",
  "portretten",
  "prentkunst",
  "rationalisme",
  "realisme",
  "regionale kunst",
  "religieuze architectuur",
  "religieuze gebouwen",
  "religieuze kunst",
  "rembrandt",
  "reproducties",
  "rijksmonument",
  "rotterdam",
  "schilderkunst",
  "schoenen",
  "school van barbizon",
  "sieraden",
  "slavernijverleden",
  "sleutelwerk",
  "speelkunst",
  "spel",
  "sportcomplexen",
  "staal",
  "stad",
  "stadsicoon",
  "stadsvernieuwing",
  "stedelijk",
  "stedenbouw",
  "stedenbouwkundige plannen",
  "stilleven",
  "straatfotografie",
  "straatkunst",
  "straatmeubilair",
  "street art",
  "streetart",
  "stripkunst",
  "structuralisme",
  "surrealisme",
  "technologie",
  "tegelkunst",
  "tekeningen",
  "tekenkunst",
  "tentoonstelling",
  "terrazzo",
  "textiel",
  "textielkunst",
  "tibetaanse kunst",
  "tijdelijk",
  "toegepaste kunst",
  "tuin",
  "tuinontwerp",
  "utiliteitsbouw",
  "venetië",
  "verbeelding",
  "verkeersgebouwen",
  "verzamelaars",
  "video",
  "videokunst",
  "vincent van gogh",
  "volkskunst",
  "vrijstaande woonhuizen",
  "waarneming",
  "water",
  "wind",
  "winkels",
  "wisselende tentoonstelling",
  "woningbouw",
  "zandsculpturen",
  "zeekust",
  "zelf maken",
  "zero",
  "zilver",
  "zon",
  "zorg"
];
