insert into public.kk_tags(label,dimension,description) values
('kunst','collectie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('geschiedenis','collectie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('streekgeschiedenis','collectie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('natuur','collectie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('wetenschap','collectie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('techniek','collectie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('design','collectie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('archeologie','collectie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('wereldculturen','collectie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('religie','collectie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('literatuur','collectie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('muziek','collectie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('toegepaste kunst','collectie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('schilderkunst','medium','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('beeldhouwkunst','medium','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('fotografie','medium','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('tekeningen','medium','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('grafiek','medium','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('textiel','medium','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('keramiek','medium','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('glas','medium','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('sieraden','medium','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('video','medium','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('installaties','medium','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('digitale kunst','medium','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('architectuur','medium','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('oude meesters','periode','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('19e eeuw','periode','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('moderne kunst','periode','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('hedendaagse kunst','periode','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('middeleeuwen','periode','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('renaissance','periode','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('barok','periode','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('20e eeuw','periode','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('realisme','stijl','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('impressionisme','stijl','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('expressionisme','stijl','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('abstractie','stijl','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('surrealisme','stijl','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('minimalisme','stijl','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('conceptuele kunst','stijl','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('De Stijl','stijl','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('landschap','thema','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('portret','thema','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('natuur en milieu','thema','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('maatschappij','thema','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('identiteit','thema','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('migratie','thema','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('oorlog en vrede','thema','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('maritiem','thema','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('vervoer','thema','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('industrie','thema','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('mode','thema','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('ambacht','thema','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('openlucht','beleving','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('kleinschalig','beleving','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('iconisch gebouw','beleving','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('interactief','beleving','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('rustig','beleving','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('met kinderen','beleving','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('verdieping','beleving','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('experiment','beleving','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('Museumkaart','voorziening','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('rolstoeltoegankelijk','voorziening','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('museumcafé','voorziening','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('museumwinkel','voorziening','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('audiotour','voorziening','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('rondleiding','voorziening','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('stedelijk','locatie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('landelijk','locatie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('aan het water','locatie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.'),
('in een tuin','locatie','Redactionele tag; alleen toepassen na controle. Voorzieningen en toegankelijkheid vereisen een actuele bron.')
on conflict do nothing;
